---
# Kubeseal version to install
install_kubeseal_version: "0.33.0"

# URL to download the kubeseal manifest
install_kubeseal_manifest_url: |
  https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ install_kubeseal_version }}/controller.yaml

# Local path where the downloaded manifest will be stored
install_kubeseal_manifest_dest: "/tmp/k8s-kubeseal-{{ install_kubeseal_version }}.yaml"
