$ANSIBLE_VAULT;1.1;AES256
30313931636266633464303932643337653036643234323466313765373463353663383738346235
3464623439383562336534356436623739346165326532300a613534323830386235353335313166
36383230376330393931323531323465383737623431623265323730653666643539356231643332
3832383630333534390a613565306261653665313530633061383634353365353766346339376132
65336536643666396331613762393336633136306365626335316664653766393137633861313436
63306164663030386161393464343635393834303531643236613633323464366564643762616437
36333166636636663333633833656634336462323731623837343437663365366466623636376638
30383038316138653534373134633562646434666437643330643232613632623538343932623161
64376138373663323335343238653735353762383364333265386630373631613437333861613832
3764643831643666653835656133323430383262373963336131
