$ANSIBLE_VAULT;1.1;AES256
31636134356165346430323564666264383337323130353562393135306566376136376434383430
3035613230323331323331323763623831306262353239390a643265393037623536313166633536
65356162396537303863356530656531366430333130386632643364643130356466326139303734
3234386137393162650a663561383037386236343664363532343061336233346364346564323663
33613938303634666563626539656566643730313864306161663537656562633566616137353433
64313361356565343930353434346136653233393137363561626231333034386436333037383338
61613264326139313230306562376532396663356538663337346438613130656263643561366566
32383861313430386635383138646466306463666637633030363263666531393763303665306237
31323162306565393861356666343166343363633264653438366333346237356664643432613236
39333932306137613662336432623532626138346635636237346431653836383133623734356138
37306438373564353130306139343962663066376465336536666561333232636637326231616239
31373465623064346439303838396261323833386361306238306439346139393531363765376631
35646262633864333039383939636536333339383635633733636537376235336133373233653839
66386566626164373163613138356233396264333635653539303961653234323330393137346237
66343036663934323963626361326530666565323135323465353765663234646636363266376134
39613537646137356130
