$ANSIBLE_VAULT;1.1;AES256
37303633353466643430303538333061373365316231306465613532373835653836636363316362
3538663735313630353230353563323263623238323737310a613130663631636161353030303934
32656335373835373832323432343864326662333132646631393263626338306539626438623635
3533646439333532630a333734396333363638666263663962636135353566333463346665633034
64326439653636363931373239396163326433343536333463633037343738363738653032623837
37326333313135393561613931393831323033366266616265386231663964356236346136326536
39373562303164383931356363626330363738306530653632393637303530376262316630646535
36623131316662366465366439396234366235616636333533336636323638613861303632376131
36613861396331346233316538663736306636613061396136666331613439333530656531313935
64353534626435633031613638306262356364653665303435323839323761633030333166646661
62666335333136626330333165316361313763663462663934313064303234346662616435346537
65663465373862326364613832613630343365386337636565666532316239623762353466633038
65613330376239393361336164366236623534663265623634383066323364303032
