$ANSIBLE_VAULT;1.1;AES256
32643233393035356331343032623638383539613530393863663236643664316533323736396365
6534396331366636373337643538663236343634613431370a643065613261306162636439373565
65663866353663366263323862666536353933343766386235326130363238663237616635323534
6634326632333530630a643836336666323633636461613434366236613632653134303938316132
64666131313239303635316430643662326563346365626436626566313738303033636530653034
32346635346137333630363634653432666235633163303664383030366539336531356138613731
33366462336366333164333062386130623962376338363433623439336661663464333864663466
33343339353930373133623965306363623833646234356535643833313961313634666264636462
33356437666232383963613162376565343561363635393732653432343339626664653837643732
63646432626162316663633162613461656361383834636636333739323339346339643831366262
37333437303661393732363864643766626235383736313638393633303933343139353834353165
32613564316136666437626233323537623661633464643363656337663037313830356264306635
37363566346463396333303834643432333630623465636633666232336137386166313464323537
66343937623532313732663461623631303365633930346239313364613164646664316338383834
396364303262343238336238643933313931
