$ANSIBLE_VAULT;1.1;AES256
30656434386633356234363364613136336437396538633961313736633739383432343639613835
3631393462643437636436653030613663663564383439620a386561366661393138316462346639
61383665643762303038306237623735373534366162343065396532636638613632336538393332
3238383933363635390a323133373363303538386131663465626433303961333838366266373166
62613239373431343638383237313830316134663866643234346337366364396536393832333431
31636135376665333035303230633833323965356537313433636232666133333665653163313165
31613632653230396333643862623331383035646262346564316338643262623136393431656631
39653964303363363432353436616561646264306637653065316163616532313934666265646139
31626339343730323165333032666263333530306633666431353466393837666233353236346230
3035303764366164383230383661396663306364363131303838
