---
# ACME/Let's Encrypt configuration
traefik_acme_email: "katie@mulliken.net"
traefik_acme_server: "https://acme-v02.api.letsencrypt.org/directory"
# Use staging for testing: "https://acme-staging-v02.api.letsencrypt.org/directory"

# Domain for wildcard certificate
traefik_acme_domain: "corp.mulliken.net"

# Certificate resolver name (referenced in IngressRoutes)
traefik_acme_resolver: "cloudflare"
