---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB6SQVommw9d+pgk9MSHqRQVkqcB22/pH7gTlB/66oDDIO2h5lyrJJ0M6IrBrygKMHuENqpYs/ZMH35kPMGW4W9xOpmdgWl32WbYhKQRpwxDkYlS+jNApHPxcaZ5WWE1stQf+JXFMRHBvtiSeopLk1mELyXc38koJAQAy4oVLqY08y9K3n5FlCTycJ1mnC9v5UGFJiKLDc20HGB72+nN2Bq+TQjZIFwm8ZWwZaNz0SE8OfnMu8Z9EjeK/ZJun06+i25A2ugD8e8rb8AYnrom6KLWRyiWytqRYptJYkXPdRZ4FBVLOmiK26GAOqBkbSaV+jnzQ+avUNn891C039n7/AvU9c/Zs82yh8oH7FNxgDk5Fy3Bwnrlqz8fg+2bcWM/P1NtLcG8vhwA/bYnq8wIOxUp+CBJhUUVVGSAh3YMRzZdBOHOzmyBB1V3Dx3egmKsNTIPLcpM3WagnVDLkoWh1eKPCPnjzglSMEFQHEM+tdIummgZjYsqfhs4KSaP6b7l9IUXqRgkACP+EC/9nRJPbgsCEgy3i1r2uelaYztM/FX38qeFyzU+IoGDON7ixHc3EyTpisDbwHnqlcDsWM5OUZbQaEtuuzz61cPWzBIB99oH2DYzJ1aQkT7SJ3WNjoUGbLSrqGMd0bxk2D6dy+L92uC4L8NUsaJ4sFotYosHfZ55PZle0wTRgCtHEpNPhunJROSHO3nX+f9U1ye6TWWt6aVJiM5s1d2UJ0=
    admin-user: AgB5GPRsw83Igqu+2r2VOto5LAxoiEbtMRDpAVBt2HB9VY8n2676gqOo2N7ot2rD11xBi4++W17TA0yh3HniUeYDoDuYpMDpTIRELEUhzOIs6mJPK/aTE3/LRumNhnd43Br3iOzMcOUa8WBuuM1LEx3qnq8EftO71d1m9fUAemEMntX+jLF4ojHCPRSe4X0H2BivoH2yzX/mZvPcX1zk5J87LL/4ed6XeF87YTb9tfRCwsH+zETw/yR5ILfljV2CD7gxwiJvZqm0D2UnCwgdnWZjfDSff9IMqNiF3Ygev8cgfDZp7lOVDZUEIzRh3CzUMvWlOiSZTScLKke2v2cYtG7J8IjZO0glGSTFctbnA3VjKTmKoVqQZlbB+JP/ikSRKjtB/FdzwqC3gz5c6QdFYIy9kzjiDEVVF4Z9knxym5oLrTSa6aMgYIGKZZkUzIMRNGLnXbtolsITYf5H93Tm+YB0miILixhIJHtf9w9mehSBiHLWkahguVGOOn2uzyasAc6Bob6KumLe2tJQqSVJkpEaKg6mL0LSOrHGNj8SJ2ifLJsDC1uXeU70gYa6My+JnfvTiNn+INQVyb8+2tvnbrkQ4EUlxZV0NuZ16h12Sl3/UpMUtXoJugkP8oh0INsdOMR1BvEO/DtHtkCMTACamuc+27O4hu4w0U5vQVw+35rMdAf+Ygvr57GIyD4k+gkrsRtQ0HdmHw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
