---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.corp.mulliken.net`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: sonarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.corp.mulliken.net`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jackett
  namespace: sonarr
  labels:
    app.kubernetes.io/name: jackett
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jackett.corp.mulliken.net`)
      kind: Rule
      services:
        - name: downloads
          port: 9117
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: sonarr
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.corp.mulliken.net`)
      kind: Rule
      services:
        - name: downloads
          port: 8080
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/part-of: media
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.corp.mulliken.net`)
      kind: Rule
      services:
        - name: downloads
          port: 8085
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
