---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: downloads-vpn-secrets
  namespace: sonarr
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgCiwuDsMjEeHYTg5uDe6MNyi4Otl+/RwrnpBF+Yoz3XleIAAgBh66tmVWXbcQGOaQ40GY4LRpWQXNvdFuIdo/TZ1s6h1z5O7Iq86JUOESjQs+OYMweW9IRupYXaRqRTZFu2vW3+TjeQXVBejcAlWG94DIqsmk36SfJVqUNdu8qGa0at2o+uhOJLjTvAdlVvVbUE08EdT2ZF/h+jNVvIiKRpb47CmivrfGFfvOnjXqQet+RsJO4hs5jjh5GDE0F/PX0EpXsvX9me2QW44NDwqSryV0ig1gciAZQF7/1RIjFd/20lwoeIsv4dLtLURATPrXKPxrH+M4HDVKor1Z1zHrTyvCvcotxeWhZLlZ3QFyv/VvRN1tmV+7QsiqfFHmCOTst/9vS9TX++SW6X46mrtONjMGcwuAnTNiBUImueuYCgW1zpDD0/SIMq581Q348icU+E0GOG2fCZDYmpkgJT98b19LVGbuGq3x5yAomDYe8/w+lsLZMyoUZIUkMm9x2CWIUuQOVQQjdof7erRdLYYgXs5Od6GGt6x7b/X8pZTMxLskR/BmjpheEBNHgYjXzVE3Cvz9j1YLod/h+1H0/cCuwTsv2iRbs5PzWhL7I8as1uSYZpFFHyTg6YQjeZhwBrWINUINIzksSmK4q2PcQ74PNcyhT1Xy/cFm5lZu/ikjGra/RLWQuIRajWJ7r3PJp7unFlYFdWkh5RXc25944oFfU0
    WIREGUARD_PRIVATE_KEY: AgBHk1gJ+oiADmUOX7R3G7866olSPU03slDqvPaG2A+wW+UnyQzkx3DPM/Kx11IwyGAf+/bMQMo0bjeBO6JnGsjwO0lrB+5GLoZbzB3FxFHh91egL2OFMLg7sIF4FFSV6S4stWULq5JOmgOLTd7xzB2Pt9PDmhZASTaWteYbbnEcTVgHJxGuUEkjbFn0jAUs8xHND5SMxY6zHGXvqgzNiUctbhPSsFfIZWZ4MLUT82b92Wd96cfP4qTh1twBVgj+XintLqUhvHdTQssLDRj3B/kEaSrjB3G3esGt/eOz4w7GNgsibiGs+o0Czzc0bPI3+RIJUQHomnDudcpF8sP9aKqWk2Jsd6/QvjdZJH5kPmbb04EMAt4GvW7jLT6e1+bqmikno1uKl36qud6rHN5xR1RTGTFvMkjyD+Jssv+zW4fQS2sChGWmiLPlPagYS1NeNhb1lPQ9YppwsHLuy+Aqm5Lr2+lXjwtvX4Ay/yWNMGMWgyt3NaCUjvoyn5I7Au4/05T5PsF+QAjYX2kloiJStf7MhTIzgMo61dxh2f/RAUR3075iZgHJiW81QDTI8xkeb9BLaOuOjtK2BD5EhF3uFFFKJnSXtJ28xiP/w4W8a8SzkyOijGuF0o9ew7xoVFp99PbF1X4IUOQZ+0lQFHYCxQ5GIGORzN2F2dpHt9p0QRjkjqsmTwhVfPE2SeIRI3i3BYLnbLAGiSyhzL+efTOMU+cWlz5xS55PEQqQhEwSImaYPLWj1vUNgMDPdij2SA==
  template:
    metadata:
      name: downloads-vpn-secrets
      namespace: sonarr
    type: Opaque
