---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: downloads-vpn-secrets
  namespace: sonarr
spec:
  encryptedData:
    WIREGUARD_ADDRESSES: AgDbf6w8W6FhKV5SL5IeH7MOxqnQGAzud50Lbeg4DnGkpEmXV7Mxlt/yJze4zImtINiCYpvGDkq1si2lOZzE1LRLmT79PMAunzi0WdEynaMZqeaIuwHLNsFkx0TGQL5Hj0rqS+a39arst+Y+/rCpZ58OZ8guWcrpik4qi6TeL+ov7gfaVQlsZ9ByCsitRQJfacjWKNPzA97TwXGxJas8Z/I+tKU8/7V+QIFxsbBWa1YAtet7oYiqWVDYFdgBdv3eKynDx+idciknWK3X7zr9KrlMSi8SXH/TGbpSA5cRteUNcAJNw8p5FRb4fAxfM4Aj4HaOIb+EFoHxiLcG/o7qH7r6OVUe60/UWrkRUNDqsV9NczwzY7cZwjHeQWqg1GU8GSyCOwnhIPZ0BhpgrPRT+KGwCTxGqVGa/y7JLUV9npB9gH6lhji9JKNv0u2IXcJ9WM+MEMqvpxuvtGtKE4ir6+WJ168Jo24GNEyG/NTGe08jc3pxgJtwfFS98ASiZWK65WVoVHADBYF1opEl9YhDRzqsVR5usL/DD5KyL9NaUXlgYnJwnz+rItR52wMDC4og4LxoqEv96+bKmTEcVaGDDvSt5irKAv+bxAPgHj4dSY/3T42v6WXi+Zr7MC5tSsDL+QEqGa685rEQ1j5Bt2Cve3P8im46brmvTM0GmhfFDEZDgQ+me39Sm8Gzi5gqYvyZJmFPURysVgFtXNLMd89UKhWR
    WIREGUARD_PRIVATE_KEY: AgAfc1i5AdspC+E6BVqLNuARVuxaZUCZqPI2Z6tv+JnCoGR+LG/q/TgI14bfVKMICEInoBDoatXvGh3s2ofRGOMKqUFR5gaBWH8Z4jdKKM3sUXuSAuZ6XW010JsAv1l5fXpGEe/0rsrnmPOrdT73h+lurVv/NQPMRgkdNkP0HmiT42l6/EJced10UcwV7rCVWgkBIs+gN+RD317DTvNW6Gnu8dxqZYhZyTJbkn6qREXqK/pCfp5F6UYFuWrHiDWAFWbRpoo/qXLsnfZzrxYZZvKXbJSkqhnvHwMwthNd7DPo2/dGvNkM1uDtRaNS42C3ZS/kjVsamAQ2M6+ARDDPM+iSm9yU/9k83MfC7Y0ywTaWEoGKUdDSm4nQ4pI4INPSxKE6pCH/4j3UZZfaBtxKaksj2hA4ExLBdM6ZKqIKHGY2NTBRY9aeRnFuBxBB2zr6peJaNk8COoMNkPuq3c/t9WSDXlXicdGhevSwF/rIn/EwIyvXoIaE5iO6kT1uVaZ/U5nvXIT68024Feo2wwa7hZP34xbKCRpXZoUMwDIacCbwWoeoTKSSVBTgYpkMDkeZSTbrzQYHWuRN5zT1zYp0RA4ERAoXLMxm6adJtASZ8apmRx+htZWzFf/sMmzYtlBIJP4RVUwvqbzZkHkAONam67Ts8eqWL0lYGUxhpuiwepoM8VWWpTh0/ZziBKOnVaW5rNyZ26ix6tws2HCR1a4ROzSjlbCC+Dk6yU4yx14hHyoXAVoyrl5Gj+DpJdKF/Q==
  template:
    metadata:
      name: downloads-vpn-secrets
      namespace: sonarr
    type: Opaque
