---
# Node Exporter Configuration

# Namespace
node_exporter_namespace: monitoring

# Image
node_exporter_image: prom/node-exporter:v1.8.2

# Resource limits
node_exporter_cpu_request: 100m
node_exporter_cpu_limit: 200m
node_exporter_memory_request: 128Mi
node_exporter_memory_limit: 256Mi
