---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/managed-by: ansible
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.corp.mulliken.net`)
      kind: Rule
      services:
        - name: prometheus
          port: 9090
  tls:
    certResolver: cloudflare
    domains:
      - main: corp.mulliken.net
        sans:
          - "*.corp.mulliken.net"
