---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgCZXgH5zI6rix5SjPQrviwHtPQ2emYSpa7pXo4USIrSCr6ZaGZahUXlKfZDtzmAbec+ei/+RHflNRCmHfxDiTcG8sXAFj7va5FFvzmfjukdP0U9GN53Dbfqa0jt7PlcFdZ4OJsnaMueaWhTbV088/cq/UYOpZrndUmmM8V+M+ErygrugxSeANZq71JXTiqrnNrzkZcWPhNpteKozT4TvHhZpfXrZXlPw3ii+ujIpyTJMCsK0rsd9QxlR3Wi2JRj+4/+dgs4NU6fkt99MWHASNor2fBAFy9OjE+UMe5iu+iQZkX4FtuRndXdz5Ee2yfo32sITMA2Zb2LJf+dVGIEo99PceNdIybliC7tNceQ0z0Q3IpLP4Vj23WFgbT+IMcWWBpujgghrTl5NIyRf3h8m8Zvvz3ID3MKSHsDwEsXoRa9IWdglcBk4aFqFYOfUDnitLMsa/yYVPslDwkL++LDcE0GMCa1A5nCNI7ihC4P6V9/q1uGZao1byUEvtLoBm0vUhXG0QUINVEnL/hBI6xllpkeT/YiYTm+VJenki+jU3T9YmZo1p9RMBSPW2HosqrfXu72inzMbgEeDm6vCu44kDiNBgpfOaga34MT3sYOqBxv24UP9Yw9oFgyIbz7eLRMpkRbOGm3dn7yg2VARcC1JUkt6iLMgd80oiep3pZua2FYGdRdsXLi90XRxtWG351/GQldcZJKuWmdEsj8Ob+xiM/mKelOVedYSi+WcFihN7JzAOzQfQynPz6M
  template:
    metadata:
      name: cloudflare-api-token
      namespace: kube-system
    type: Opaque
