---
- name: Join new nodes to k3s cluster as agents
  hosts: new_k3s_agents
  become: true
  gather_facts: true

  roles:
    - k3s_agent

  post_tasks:
    - name: Display join completion message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} has been joined to the k3s cluster"
