---
# cert-manager configuration
cert_manager_namespace: "cert-manager"

# Helm OCI chart
cert_manager_helm_chart: "oci://quay.io/jetstack/charts/cert-manager"
cert_manager_helm_version: "v1.19.1"
cert_manager_release_name: "cert-manager"

# ClusterIssuer configuration
cert_manager_acme_email: "katie@mulliken.net"
cert_manager_acme_server: "https://acme-v02.api.letsencrypt.org/directory"

# Cloudflare DNS01 solver
cert_manager_cloudflare_api_token_secret_name: "cloudflare-api-token"
cert_manager_cloudflare_api_token_secret_key: "api-token"
